# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual trigger

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: # Build the React application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      # --- Use the official Bun setup action ---
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        # Optionally specify a bun version, defaults to latest
        # with:
        #   bun-version: latest

      # --- Install dependencies using Bun ---
      - name: Install Dependencies
        run: bun install

      # --- Build the site using Bun ---
      # This command should match your package.json build script
      - name: Build Site
        run: bun run build

      # --- Upload artifact for GitHub Pages ---
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the build output directory specified in vite.config.js (usually 'dist')
          path: ./dist

  deploy: # Deploy the artifact to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
